name: Feature Request
description: Request a feature that you would like to see in clCord
labels: [enhancement]

body:
- type: markdown
  attributes:
    value: |
      - Check if the feature was already requested [here](https://github.com/tibue99/clcord/issues).
      - Include only one feature per issue.

- type: textarea
  attributes:
    label: Feature Description
    description: Please describe the feature as detailed as possible. Feel free to include examples.
  validations:
    required: true
